version: "2"
services:
  web:
    build: ./src/web
    ports:
      - "80:80"
  server:
    build: ./src/server
    ports:
      - "3001:3001"
  db:
    image: "mongo:3.6.2"
    volumes:
     - ./data/db:/data/db