version: "2"
services:
  web:
    build: ./src/web
    ports:
      - "3000:3000"
  server:
    build: ./src/server
    ports:
      - "3001:3001"
  db:
    image: "mongo:latest"
    volumes:
     - ./data/db:/data/db